name: montagu-letters
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - matplotlib
  - seaborn
  - numpy
  - python>=3.13
  - ipykernel
  - scikit-learn
  - nltk
  - gensim
  - pandas
  - python-dotenv
  - spacy
  - lxml
  - requests
  - beautifulsoup4
  - conda-forge::ipywidgets
  - conda-forge::cryptography # some issues pop up due to google-genai 
  - pip  # Add pip to install packages not in conda
  - pip:
      - google-genai  # google-genai must be installed via pip
      - pypdf
      - wordcloud
      - tqdm
      - folium # creates interactive maps (Leaflet.js-based)
      - stanza