name: montagu-letters
channels:
  - conda-forge
dependencies:
  - jupyter
  - matplotlib
  - seaborn
  - numpy<2.0
  - python=3.12
  - ipykernel
  - scikit-learn
  - nltk
  - gensim
  - pandas
  - python-dotenv
  - spacy
  - lxml
  - requests
  - beautifulsoup4
  - ipywidgets
  - cryptography
  - pip
  - pip:
      - google-genai
      - pypdf
      - wordcloud
      - tqdm
      - folium
      - stanza>=1.8,<2.0